// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/histogram": {
            "get": {
                "description": "Generate a histogram with the fares",
                "produces": [
                    "image/svg+xml"
                ],
                "summary": "Get histogram",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {}
                    }
                }
            }
        },
        "/passenger": {
            "get": {
                "description": "Get all passengers of the database",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all passengers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Passenger"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/passenger/{id}": {
            "get": {
                "description": "Get a passenger by key and filter fields (optional)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a passenger by key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key of the passenger",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Passenger"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Passenger": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "string"
                },
                "cabin": {
                    "type": "string"
                },
                "embarked": {
                    "type": "string"
                },
                "fare": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "parch": {
                    "type": "string"
                },
                "passenger_id": {
                    "type": "string"
                },
                "pclass": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "sibSp": {
                    "type": "string"
                },
                "survived": {
                    "type": "string"
                },
                "ticket": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BMC-assignment 2023-08-29",
	Description:      "BMC Histogram CSV SQLite Docker",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
